### ISSUE TITLE
Use templates to map user attributes

### ISSUE THREAD

**Issue by matrixbot** [element-hq/matrix-authentication-service#2066]
*This issue was originally created by [**@sandhose**](https://github.com/sandhose) at <https://github.com/matrix-org/matrix-authentication-service/issues/2066>.*

We currently import the displayname, localpart and email with static attributes. We should instead use minijinja templates for those instead, and check whether we're compatible with what Synapse is doing

Sample config:

```yaml
upstream_oauth2:
  providers:
    - issuer: x
      attributes:
        subject:
          template: "{{ user.sub }}"
        display_name:
          action: import
          template: "{{ user.name }}"
        localpart:
          action: force
          template: "{{ user.sub }}"
        email:
          action: suggest
          template: "{{ user.email }}"
   
```
