### ISSUE TITLE
unable to set up MAS with existing homeserver and Authentik as OIDC

### ISSUE THREAD

**Issue by ghostklart** [element-hq/matrix-authentication-service#3613]
**Describe the bug**
After setting up both containers following the guide, I'm not able to login to my element instance with error.

**To Reproduce**
1. Set up the mas container with config following the guide
2. Update homeserver according to guide
3. Run syn2mas (which migrates successfully)
4. Try to login to MAS/auth - ends with success
5. Logging to web gui of element/desktop app fails with error

Error from element web (probably sent from synapse server):
```
{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}
```

Error from homeserver:
`synapse-server  | 2024-12-02 17:17:56,448 - synapse.http.client - 441 - INFO - GET-2662 - Received response to POST https://auth.<redacted>.com/oauth2/introspect: 401
synapse-server  | 2024-12-02 17:17:56,449 - synapse.api.auth.msc3861_delegated - 338 - ERROR - GET-2662 - Failed to introspect token
synapse-server  | Traceback (most recent call last):
synapse-server  |   File "/usr/local/lib/python3.12/site-packages/synapse/api/auth/msc3861_delegated.py", line 336, in get_user_by_access_token
synapse-server  |     introspection_result = await self._introspect_token(token)
synapse-server  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-server  |   File "/usr/local/lib/python3.12/site-packages/synapse/api/auth/msc3861_delegated.py", line 246, in _introspect_token
synapse-server  |     raise HttpResponseException(
synapse-server  | synapse.api.errors.HttpResponseException: 401: Unauthorized
synapse-server  | 2024-12-02 17:17:56,449 - synapse.http.server - 130 - INFO - GET-2662 - <XForwardedForRequest at 0x79753d9c7470 method='GET' uri='/_matrix/client/v3/sync?filter=0&timeout=0&set_presence=unavailable&since=s8779_4412267_0_23741_6353_12_847_57460_0_10' clientproto='HTTP/1.1' site='8008'> SynapseError: 503 - Unable to introspect the access token`

Homserver config:
```
server_name: "matrix.domain.org"
suppress_key_server_warning: true
pid_file: /data/homeserver.pid

presence:
  enabled: true

experimental_features:
  msc4108:
    enabled: true
  msc4222:
    enabled: true
  msc3266:
    enabled: true
  msc3861:
    enabled: true
    issuer: "https://auth.domain.org"
    client_id: "0000000000000000000SYNAPSE"
    client_auth_method: client_secret_basic
    client_secret: <redacted>
    admin_token: <redacted>
    account_management_url: "https://auth.domain.org/account"

instance_map:
  main:
    host: 'synapse-server'
    port: 9093
  synapse-worker-1:
    host: 'synapse-worker-1'
    port: 9093
  synapse-federation-1:
    host: 'synapse-federation-1'
    port: 9093
  synapse-background-1:
    host: 'synapse-background-1'
    port: 9093
  
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
  - port: 8081
    type: http
    resources:
      - names: [health]
  - port: 9093
    type: http
    resources:
      - names: [replication]

worker_replication_secret: "<redacted>"

database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: synapse
    password: <redacted>
    database: synapse
    host: postgres
    port: 5432
    cp_min: 20
    cp_max: 100

redis:
  enabled: true
  host: redis
  port: 6379

media_store_path: /mnt/media_store

report_stats: true

max_upload_size: 4G
enable_registration: false
password_config:
  enabled: false
registration_shared_secret: "<redacted>"
matrix_synapse_federation_enabled: true
matrix_synapse_federation_port_enabled: true
search_all_users: true
prefer_local_users: true

turn_uris:
  - "turn:turn.domain.org?transport=udp"
  - "turn:turn.domain.org?transport=tcp"
turn_shared_secret: "<redacted>"
turn_user_lifetime: 86400000

tls_certificate_path: /caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/matrix.domain.org/matrix.domain.org.crt
tls_private_key_path:  /caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/matrix.domain.org/matrix.domain.org.key
signing_key_path: /data/matrix.domain.org.signing.key
server_server_wellknown: true

trusted_key_servers:
  - server_name: "matrix.domain.org"
  - server_name: "matrix.org"
default_identity_server: https://matrix.org
trusted_third_party_id_servers:
  - https://matrix.org
  - https://vector.im
  - https://matrix.domain.org

email:
  smtp_host: "<redacted>"
  smtp_port: "<redacted>"
  smtp_user: "<redacted>"
  smtp_pass: "<redacted>"
  app_name: "<redacted>"
  enable_notifs: true
  notif_from: "<redacted>"
  notif_for_new_users: true
  client_base_url: "https://matrix.domain.org"
  validation_token_lifetime: 15m
  enable_tls: true
  require_transport_security: false

admin_users:
  - "@<redacted>:matrix.domain.org"

encryption_enabled_by_default_for_room_type: "all"

# offload main server
send_federation: false
federation_sender_instances:
  - synapse-federation-1
outbound_federation_restricted_to:
  - synapse-federation-1

update_user_directory_from_worker: synapse-background-1
notify_appservices_from_worker: synapse-background-1

start_pushers: false
pusher_instances:
  - synapse-background-1
```

Spamming error in MAS logs:
`synapse-auth  | 2024-12-02T17:18:43.633602Z ERROR http.server.request{otel.kind="server" otel.name="POST /oauth2/introspect" network.protocol.name="http" network.protocol.version="1.1" http.request.method="POST" url.path="/oauth2/introspect" url.scheme="http" http.route="/oauth2/introspect" user_agent.original="Synapse/1.120.0"}:handlers.oauth2.introspection.post{client.id="0000000000000000000SYNAPSE"}: mas_handlers::oauth2::introspection: crates/handlers/src/oauth2/introspection.rs:161: error=could not find client`

MAS config:
```
http:
  listeners:
  - name: web
    resources:
    - name: discovery
    - name: human
    - name: oauth
    - name: compat
    - name: graphql
    - name: assets
    binds:
    - address: '[::]:8080'
    proxy_protocol: false
  - name: internal
    resources:
    - name: health
    binds:
    - host: localhost
      port: 8081
    proxy_protocol: false
  trusted_proxies:
  - 192.168.0.0/16
  - 172.16.0.0/12
  - 10.0.0.0/10
  - 127.0.0.1/8
  - fd00::/8
  - ::1/128
  public_base: "https://auth.domain.org"  
  issuer: "https://auth.domain.org"
database:
  host: postgres
  port: 5432
  username: synapse
  password: <redacted>
  database: matrix
  max_connections: 100
  min_connections: 20
  connect_timeout: 180
  idle_timeout: 600
  max_lifetime: 1800
client_secret:
  - client_id: "0000000000000000000SYNAPSE"
    client_auth_method: client_secret_basic
    client_secret: <redacted>
email:
  from: '"Authentication Service" <<redacted>>'
  reply_to: '"Authentication Service" <<redacted>>'
  transport: "smtp"
  mode: "tls"
  hostname: "<redacted>"
  port: <redacted>
  username: "<redacted>"
  password: "<redacted>"
secrets:
  encryption: <redacted>
  keys:
  - kid: <redacted>
    key: <redacted>
  - kid: <redacted>
    key: <redacted>
  - kid: <redacted>
    key: <redacted>
  - kid: <redacted>
    key: <redacted>
passwords:
  enabled: false
  schemes:
  - version: 1
    algorithm: argon2id
  minimum_complexity: 3
matrix:
  homeserver: "matrix.domain.org"
  secret: <redacted>
  endpoint: "https://matrix.domain.org:443"
account:
  password_change_allowed: true
  password_recovery_enabled: true
upstream_oauth2:
  providers:
    - id: <redacted>
      discovery_mode: insecure
      human_name: authentik
      issuer: "https://authentik.domain.org/application/o/matrix-synapse/"
      client_id: "<redacted>"
      client_secret: "<redacted>"
      scope: "openid profile email"
      token_endpoint_auth_method: client_secret_basic
      claims_import:
        localpart:
          action: require
          template: "{{ user.preferred_username }}"
        displayname:
          action: require
          template: "{{ user.name|capitalize }}"
        email:
          action: require
          template: "{{ user.email }}"
          set_email_verification: always
```

**Expected behavior**
Successfully login to my existing user and see all chats

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser brave
 - Version v1.73.91
