### ISSUE TITLE
No Documentation for QR Code Login

### ISSUE THREAD

**Issue by SNThrailkill** [element-hq/matrix-authentication-service#3743]
Would anyone be able to share the configuration needed in both Synapse and MAS to get QR code login available? If I try to link a new device it says QR code not supported. `Your account provider doesn't support signing into a new device with a QR code.` and I can find no documentation on this. Ive enabled the experimental MSC in the config and everything else seems to work. Or does this feature abandoned which is why its not documented?

**Comment by akarl10** [comment]
@SNThrailkill If you still try to enable qr code login but element web says it's not available:
The only thing I needed to add
```yaml
experimental_features:
    msc4108_enabled: true
```
(of course the experimental_features: contains more entries, but I added it to make it clear where to put)

to take effect msc3861 must be enabled, but since you write this in the issue for mas I am sure you have this.

**Comment by enekonieto** [comment]
Not working for me using Keycloak as upstream IdP.

```
experimental_features:
  msc3861:
    account_management_url: https://matrix.***/auth/account
    admin_token: ***
    client_auth_method: client_secret_basic
    client_id: 0000000000000000000SYNAPSE
    client_secret: ***
    enabled: true
    introspection_endpoint: http://matrix-authentication-service:8080/auth/oauth2/introspect
    issuer: http://matrix-authentication-service:8080/auth/
  msc4108_enabled: true
```

Does Keycloak support this? Do I need some special config in Keycloak? I used the sample Keycloak config: https://element-hq.github.io/matrix-authentication-service/setup/sso.html#keycloak
