### ISSUE TITLE
syn2mas advisor timeout error

### ISSUE THREAD

**Issue by Tazy-Repo** [element-hq/matrix-authentication-service#3941]
**Describe the bug**
I get a timeout error when running the syn2mas advisor command
```
~$ syn2mas --command=advisor --synapseConfigFile=homeserver.yaml
[2025-02-03T01:08:55.471] [ERROR] default - KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/usr/local/lib/node_modules/@vector-im/syn2mas/node_modules/knex/lib/client.js:332:26)
    at async Runner.ensureConnection (/usr/local/lib/node_modules/@vector-im/syn2mas/node_modules/knex/lib/execution/runner.js:305:28)
    at async Runner.run (/usr/local/lib/node_modules/@vector-im/syn2mas/node_modules/knex/lib/execution/runner.js:30:19)
    at async count (file:///usr/local/lib/node_modules/@vector-im/syn2mas/dist/advisor.mjs:49:21)
    at async advisor (file:///usr/local/lib/node_modules/@vector-im/syn2mas/dist/advisor.mjs:55:24)
    at async file:///usr/local/lib/node_modules/@vector-im/syn2mas/dist/index.js:43:9 {
  sql: undefined,
  bindings: undefined
}
```
**To Reproduce**
run command `syn2mas --command=advisor --synapseConfigFile=homeserver.yaml`

**Screenshots**

![Image](https://github.com/user-attachments/assets/4671f155-f37a-47aa-9fa3-bb024e2084bc)

**Additional context**
I have my stack setup in docker I have created an empty db in the postgres that synapse uses
my homeserver config is here
```
server_name: "server.name"
web_client_location: https://chat.domain/
public_baseurl: https://hs.domain
pid_file: /data/homeserver.pid
report_stats: false
serve_server_wellknown: true
listeners:
  - port: 8448
    tls: true
    type: http
    resources:
      - names: [client, federation]

  - port: 8008
    tls: false
    type: http
    x_forwarded: true
#    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false

####Federation####
federation_domain_whitelist:
    - matrix.org

####TLS####
tls_certificate_path: "/data/hs.domain.fullchain.pem"
tls_private_key_path: "/data/hs.domain.privkey.pem"

media_retention:
    local_media_lifetime: 90d
    remote_media_lifetime: 1d

database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: secret
    password: secret
    dbname: secret
    host: db
    port: 5432
    cp_min: 5
    cp_max: 10
log_config: "/data/homeserver.log.config"
media_store_path: /data/media_store
signing_key_path: "/data/homeserver.signing.key"
key_refresh_interval: 2d
trusted_key_servers:
  - server_name: "matrix.org"

####registration####
enable_registration: true
enable_registration_without_verification: false
registration_requires_token: true
registration_shared_secret: secret
bcrypt_rounds: 14
default_identity_server: https://matrix.org
#macaroon_secret_key: secret

####ROOMS####
encryption_enabled_by_default_for_room_type: invite
user_directory:
    enabled: true
    search_all_users: true
    prefer_local_users: true
    show_locked_users: true
server_notices:
  system_mxid_localpart: notices
  system_mxid_display_name: "Server Notices"
  #system_mxid_avatar_url: ""
  room_name: "Server Notices"
  room_avatar_url: "mxc://example.com/oumMVlgDnLYFaPVkExemNVVZ"
  room_topic: "Room used by your server admin to notice you of important information"
  auto_join: true

####SSO####
oidc_providers:
  - idp_id: keycloak
    idp_name: "SSO Auth"
    issuer: "https://auth.domain/realms/master"
    client_id: "synapse"
    client_secret: "secret"
    scopes: ["openid", "profile"]
    user_mapping_provider:
      config:
        localpart_template: "{{ user.preferred_username }}"
        display_name_template: "{{ user.name }}"
    backchannel_logout_enabled: true # Optional

####User Session Management####
session_lifetime: 12h
refreshable_access_token_lifetime: 10m
refresh_token_lifetime: 6h
nonrefreshable_access_token_lifetime: 12h
ui_auth:
    session_timeout: "15s"

####Metrics####
enable_metrics: true

```
