### ISSUE TITLE
Using an empty prefix (or /) in an http.listeners in the configuration crashes on startup

### ISSUE THREAD

**Issue by sandhose** [element-hq/matrix-authentication-service#4068]
Since 0.14.0, the following configuration crashes the server on startup:

```yaml
http:
  listeners:
    - name: "web"
      prefix: "/"
      resources:
        - name: discovery
        - name: human
        - name: oauth
        - name: assets
        - name: compat
        - name: graphql
        - name: adminapi
      binds:
        - address: "[::]:1234"
    - name: "internal"
      resources:
        - name: health
        - name: prometheus
      binds:
        - host: localhost
          port: 2345
```

with the following message:

```
thread 'main' panicked at crates/cli/src/server.rs:243:32:
Nesting at the root is no longer supported. Use merge instead.
```

The workaround is to remove the `prefix` property, or set it to `null`/`~`

```yaml
http:
  listeners:
    - name: "web"

      # Comment it out
      #prefix: "/"

      # Set it to ~
      prefix: ~

      # Set it to null
      prefix: null
```
