### ISSUE TITLE
Policy data for emails and registration *must* be set

### ISSUE THREAD

**Issue by turt2live** [element-hq/matrix-authentication-service#4155]
**Describe the bug**
https://element-hq.github.io/matrix-authentication-service/reference/configuration.html#policy says that if `emails` or `registration` are unspecified, then the allow rules by default allow everything, but this appears to not be the case.

**To Reproduce**
1. Create a relatively basic/standard config with:
   ```yaml
   policy:
     data:
       client_registration:
         allow_insecure_uris: true
         allow_missing_contacts: true
       admin_users: ['admin']
       admin_clients: ['CLIENTID']
   ```
2. Navigate to registration page
3. Try to register

**Expected behavior**
Registration works. Instead, you're denied.

Adding this to the config fixed it:
```yaml
policy:
  data:
    # ... fields from above go here ...
    emails:
      allowed_addresses:
        substrings: [""]
    registration:
      allowed_usernames:
        substrings: [""]
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/14dbabf9-31bb-4a4d-8254-bb8095b7dd52)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 133

**Additional context**

I'm running the Docker container at https://github.com/element-hq/matrix-authentication-service/pull/4115
