### ISSUE TITLE
New created account by mas-cli can't login with initial password set by admin

### ISSUE THREAD

**Issue by chrissi55** [element-hq/matrix-authentication-service#4427]
**Describe the bug**

**To Reproduce**
1. login to your mas server (e.g. auth.domain.com)
2. go to your mas-cli binary directory (e.g. /usr/local/bin/mas-cli
3. create a new account by: mas-cli manage register-user -A -e [set-an-email-address] -p [set-an-initial-password] -d [set-a-display-name] USERNAME
5. use a password with e.g. 8 characters (containing min 1 number, 1 upper-case, 1-lower-case, 1 special)
6. check that mas-cli responds with a successful new account creation
7. try to login your new account in e.g. element-web -> after choosing correct matrix-server address -> continue to login with MAS
8. enter new-account-name (makes no diff if entered as "name" or "@name:your-server-FQDN"
9. enter the initial password given by MAS admin
10. i get a login failure that username and/or password are incorrect (login failed)
11. at least try a password reset by using "i forgot my passoword" 
12. set as recovery email address the given address by the MAS admin during account creation
13. get the recovery link by email
14. enter as "new" password the same pass than the initial one
15. i got information that the 8 character pass (containing .. see above) does not fit complexity
16. changed password to "initial-one-with-8characters plus 4 more numbers" -> reset
17. after a successful reset try again to login to element-web -> MAS by name + resetet-password
18. have a successful login

**Expected behavior**
I expected that the successful creation of the new account with an initial password works for the user directly without need to revover initial password by an individual one.
This step should be issued later after successful login to element in account settings by the user him-/herself.
If a password with e.g. 8 digits is too short for element clients this should lead to an advice in mas-cli during account creation as well -> so the MAS admin will set a password with higher complexity / more digits

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ZorinOS 17.3
 - Browser [e.g. chrome, safari] Vivaldi (x64)
 - Version [e.g. 22] 7.3.3635.11
 - Element-Web 1.11.97

**Smartphone (please complete the following information):**
didn't try an Element X on Android or iPad

**Additional context**
[Add any other context about the problem here.]
(https://matrix.to/#/!dlUJvnxTqziXgGwAaW:matrix.org/$YVwTCQEeW6eCOUeZeBwRqCuQCCgb0AQMvAoBdoiGeAY?via=matrix.org&via=element.io&via=envs.net)

Created this Bug-report after reporting this issue in the matrix auth & identity room.

my config.yaml for mas contains the following lines
```

passwords:
  enabled: true
  schemes:
  - version: 1
    algorithm: bcrypt
  - version: 2
    algorithm: argon2id
  minimum_complexity: 3
```

and as well

```
account:
  # Whether users are allowed to change their email addresses.
  #
  # Defaults to `true`.
  email_change_allowed: true

  # Whether users are allowed to change their display names
  #
  # Defaults to `true`.
  # This should be in sync with the policy in the homeserver configuration.
  displayname_change_allowed: false

  # Whether to enable self-service password registration
  #
  # Defaults to `false`.
  # This has no effect if password login is disabled.
  password_registration_enabled: false

  # Whether users are allowed to change their passwords
  #
  # Defaults to `true`.
  # This has no effect if password login is disabled.
  password_change_allowed: true

  # Whether email-based password recovery is enabled
  #
  # Defaults to `false`.
  # This has no effect if password login is disabled.
  password_recovery_enabled: true
```
