### ISSUE TITLE
[Feature request] Add an option to bypass the `openid` scope

### ISSUE THREAD

**Issue by Candinya** [element-hq/matrix-authentication-service#4457]
## **Is your feature request related to a problem? Please describe.**

We are trying to migrate to MAS for authentication, but when setting up with an OAuth2 provider (incompatible with OpenID), even with specified scopes setting, it will add `openid` to it at request, which is unacceptable by the upstream provider.

## **Describe the solution you'd like**

Add an option to bypass this additional `openid` scope, use just specified scopes provided by config.

## **Describe alternatives you've considered**

The SSO authentication mechanisms in Synapse works well. Relevant configurations has been attached below.

## **Additional context**

Synapse SSO configuration (which works well):
```yaml
oidc_providers:
  - idp_id: misskey
    idp_name: Misskey
    idp_brand: "one.nya.misskey"
    discover: false
    issuer: "https://dev.nya.one"
    client_id: <CLIENT_ID>
    client_secret: <CLIENT_SECRET>
    pkce_method: "always"
    authorization_endpoint: "https://dev.nya.one/oauth/authorize"
    token_endpoint: "https://dev.nya.one/oauth/token"
    userinfo_endpoint: "https://dev-api.nya.one/i"
    scopes: ["read:account"]
    user_mapping_provider:
      config:
        subject_claim: "id"
        localpart_template: "{{ user.username }}"
        display_name_template: "{{ user.name }}"
```

MAS configuration (which will add `openid` scope and cause error):
```yaml
upstream_oauth2:
  providers:
    - id: "<PROVIDER_ID>"
      human_name: Misskey
      brand_name: misskey
      discovery_mode: disabled
      pkce_method: always
      fetch_userinfo: true
      # issuer: "https://dev.nya.one"
      token_endpoint_auth_method: "client_secret_post"
      client_id: "<CLIENT_ID>"
      client_secret: "<CLIENT_SECRET>"
      authorization_endpoint: "https://dev.nya.one/oauth/authorize"
      token_endpoint: "https://dev.nya.one/oauth/token"
      userinfo_endpoint: "https://dev-api.nya.one/i"
      scope: "read:account"
      claims_imports:
        subject:
          template: "{{ userinfo_claims.id }}"
        localpart:
          action: require
          template: "{{ userinfo_claims.username }}"
        displayname:
          action: suggest
          template: "{{ userinfo_claims.name }}"
        email:
          action: suggest
          template: "{{ userinfo_claims.email }}"
```
