### ISSUE TITLE
Upstream account provider returned "<reducted>" as username, which is not linked to that upstream account

### ISSUE THREAD

**Issue by alexander-potemkin** [element-hq/matrix-authentication-service#4506]
**Describe the bug**
User could not login into the system.

**To Reproduce**
1. Go to mas_domain_Name
2. Click on 'My account'
4. See error: `Upstream account provider returned "<reducted>" as username, which is not linked to that upstream account` (and `Localpart template returned an existing username username=<reducted> user_id=<reducted>` on the server side)

**Expected behavior**
MAS to work, as expected, and as it works for everyone else.

**Screenshots**
N/A

Any system.

**Additional context**
For some reason, `upstream_oauth_links.user_id` was not there - I worked around that issue by `UPDATE upstream_oauth_links SET user_id='user_id_from_users_table' where subject='<user>';` - hope that was correct.

I can't see how / why this user encountered the issue - the only difference from the others that I see, it's that he was not logging in for quite a while (90+ days).

**Comment by ahmeedev** [comment]
i've created a user using SIGNUP button and added a email, but now i'm trying to sign-in using 'continue with google' and getting this same issue, 

<img width="380" height="296" alt="Image" src="https://github.com/user-attachments/assets/c136b337-8355-42e1-94e9-c00443154a1a" />

**Comment by alexander-potemkin** [comment]
Apologies, but with that issue opened it doesn't look like 1.0 version to me

@sandhose please, let me draw your attention on that and if you are not the right person - that you could, probably, re-ping someone else?

**Comment by alexander-potemkin** [comment]
> Sorry that we're not doing a better job at triaging issues. **This is the expected default behaviour**, we don't want a misconfiguration in claims mapping to allow taking over an account. There is a configuration option to allow linking of existing accounts: https://element-hq.github.io/matrix-authentication-service/setup/sso.html#allow-linking-existing-user-accounts

Thank you for responding and for letting know on the configuration issue on my side - much appreciated!


Am I correct in understanding that, given I control the authentication, I shall add:

`    on_conflict: add`

To 
```
   claims_imports:
        localpart:
```

in my config, resulting it to look something like:

```yaml
upstream_oauth2:
  providers:
  - id: <...>
   <...>
    discovery_mode: oidc
    claims_imports:
        localpart:
          action: require
          on_conflict: add
          template: "{{ user.preferred_username }}"
        displayname:
          action: suggest
          template: "{{ user.name }}"
        email:
          action: suggest
          template: "{{ user.email }}"
          set_email_verification: always
```

If so - I guess that raise another question: shouldn't have the migration process migrate all users, so that they shouldn't be created (and hence - that configuration be needed)? Or am I missing something?
