### ISSUE TITLE
`syn2mas` can't detect related oath providers

### ISSUE THREAD

**Issue by orzklv** [element-hq/matrix-authentication-service#4597]
**Describe the bug**
While trying to migrate synapse db to mas, I'm hitting this error over and over:

![Image](https://github.com/user-attachments/assets/d273aae0-7e72-4fb3-8f58-bfc36ae37d24)

The thing is, I have both of these providers set up in my mas configs:

```yaml
upstream_oauth2:
  providers:
    - id: "01HFS67GJ145HCM9ZASYS9DC3J"
      human_name: GitHub
      brand_name: github
      issuer: https://github.com/
      discovery_mode: disabled
      fetch_userinfo: true
      token_endpoint_auth_method: "client_secret_post"
      client_id: "..."
      client_secret: "..."
      authorization_endpoint: "https://github.com/login/oauth/authorize"
      token_endpoint: "https://github.com/login/oauth/access_token"
      userinfo_endpoint: "https://api.github.com/user"
      scope: "read:user"
      claims_imports:
        subject:
          template: "{{ userinfo_claims.id }}"
        displayname:
          action: suggest
          template: "{{`{{ userinfo_claims.name }}"
        localpart:
          action: ignore
        email:
          action: suggest
          template: "{{ userinfo_claims.email }}"
        account_name:
          template: "@{{ userinfo_claims.login }}"
    - id: "01HFS67GJ145HCM9ZASSSCDX32"
      human_name: Mastodon
      brand_name: mastodon
      issuer: https://social.floss.uz/@orzklv
      discovery_mode: disabled
      fetch_userinfo: true
      token_endpoint_auth_method: "client_secret_post"
      client_id: "..."
      client_secret: "..."
      authorization_endpoint: "https://social.floss.uz/oauth/authorize"
      token_endpoint: "https://social.floss.uz/oauth/token"
      userinfo_endpoint: "https://social.floss.uz/api/v1/accounts/verify_credentials"
      scope: "read"
      claims_imports:
        subject:
          template: "{{ userinfo_claims.id }}"
        displayname:
          action: suggest
          template: "{{`{{ userinfo_claims.name }}"
        localpart:
          action: ignore
        email:
          action: suggest
          template: "{{ userinfo_claims.email }}"
        account_name:
          template: "@{{ userinfo_claims.login }}"
```

here goes homeserver configuration:

```yaml
oidc_providers:
  - idp_id: github
    idp_name: Github
    idp_brand: "github"
    discover: false
    issuer: "https://github.com/"
    client_id: "..."
    client_secret: "..."
    authorization_endpoint: "https://github.com/login/oauth/authorize"
    token_endpoint: "https://github.com/login/oauth/access_token"
    userinfo_endpoint: "https://api.github.com/user"
    scopes: ["read:user"]
    user_mapping_provider:
      config:
        subject_claim: "id"
        localpart_template: "{{ user.login }}"
        display_name_template: "{{ user.name }}"
  - idp_id: mastodon
    idp_name: Mastodon
    idp_brand: "mastodon"
    discover: false
    issuer: "https://social.floss.uz/@orzklv"
    client_id: "..."
    client_secret: "..."
    authorization_endpoint: "https://social.floss.uz/oauth/authorize"
    token_endpoint: "https://social.floss.uz/oauth/token"
    userinfo_endpoint: "https://social.floss.uz/api/v1/accounts/verify_credentials"
    scopes: ["read"]
    user_mapping_provider:
      config:
        subject_template: "{{ user.id }}"
        localpart_template: "{{ user.username }}"
        display_name_template: "{{ user.display_name }}"
```

and yet, syn2mas keeps complaining about missing oath2 providers... or am I missing something from docs?

Synapse version: 1.130.0
MAS version: 0.16.0
